#!/bin/bash
# This program is free software. You can redistribute it and/or modify it under
# the same terms as perl itself. Copyright © 2011 M. Kristall

## Exit statuses
# 1		no or invalid config
# 2		config error
# 3		executioner error
# 255		potential error

## Config variables
# EXEC		(executioner) functions to control the server
# SERVER	full path to tremded to execute
# DEFAULT_PIDFILE
#		the default pid file used by the server, if applicable
# DEDICATED	dedicated mode to use
# BASEPATH	fs_basepath
# HOMEPATH	fs_homepath
# GAMENAME	fs_game
# ARGS		additional arguments to pass to server

## EXEC functions
# Cmd		exec a command on the server
#	arguments=command to exec
# Start		start the server
#	arguments=optional extra arguments to server (after ARGS)
# Stop		stop the server
#	arguments=optional message to send
# Restart	restart the server
#	arguments=optional extra arguments to server (after ARGS)

_PATH="$(dirname "$0")"
_NAME="$(basename "$0")"
. "$_PATH/configuration"
. "$_PATH/functions"

config="$1"
shift 1

if [[ "$config" == "" ]]; then
	warn "$_NAME config cmd [args]"
	exit 1
fi

cmds=()
cmd_start () {
	if getpid; then
		if isrunning; then
			warn "$_NAME: server already running pid=$PID"
			exit 255
		fi
		rm -f "$PIDFILE" &> /dev/null
	fi
	Start $ARGS "$@"
	if getpid; then
		echo "server pid=$PID"
	fi
}

cmd_restart () {
	Restart $ARGS "$@"
	if getpid; then
		echo "server pid=$PID"
	fi
}
push cmds start cmd_start
push cmds restart cmd_restart
push cmds stop Stop
push cmds reload Reload
push cmds exec Cmd

cmd="$1"
shift 1

# load plugins late
if [ ! -z "$_PLUGINPATH" ] && [ -d "$_PLUGINPATH" ]; then
	echo "Loading plugins…"
	shopt -s nullglob
	for plugin in "$_PLUGINPATH/"*; do
		echo "	$(basename "$plugin")"
		. "$plugin"
	done
fi

err=
for (( i = 0; i < ${#cmds[@]}; i += 2 )); do
	if (( i > 0 )); then
		err="$err|${cmds[$i]}"
	else
		err="${cmds[$i]}"
	fi
	if [[ "$cmd" == "${cmds[$i]}" ]]; then
		readconfig "$config"
		"${cmds[$i + 1]}" "$@"
		exit 0
	fi
done

warn "$_NAME $config $err [args]"
exit 255
